import MovieClip from 'openfl/display/MovieClip';
import TextField from 'openfl/text/TextField';
import { Button_CLIP } from './Button_CLIP';
import { buttonClose_CLIP } from './buttonClose_CLIP';
import { creatureBar } from './creatureBar';
import { frame_CLIP } from './frame_CLIP';
import { HatcheryMonsterIcon_CLIP } from './HatcheryMonsterIcon_CLIP';
import { ScrollSet_CLIP } from './ScrollSet_CLIP';

/**
 * HATCHERYCCPOPUP_CLIP - CLIP class for hatchery CC popup
 * Converted from ActionScript to TypeScript
 */
export class HATCHERYCCPOPUP_CLIP extends MovieClip {
    public tHousingLabel: TextField;
    public mcRemove6: buttonClose_CLIP;
    public hatchery5: HatcheryMonsterIcon_CLIP;
    public mcCount4: MovieClip;
    public mcRemove5: buttonClose_CLIP;
    public mcCount5: MovieClip;
    public hatchery2: HatcheryMonsterIcon_CLIP;
    public hatcheryBG4: MovieClip;
    public monsterCanvas: MovieClip;
    public mcRemove4: buttonClose_CLIP;
    public mcMonsterInfo: MovieClip;
    public hatchery3: HatcheryMonsterIcon_CLIP;
    public mcCount2: MovieClip;
    public hatcheryBG5: MovieClip;
    public monsterMask: MovieClip;
    public mcCount3: MovieClip;
    public hatchery1: HatcheryMonsterIcon_CLIP;
    public bProgress5: creatureBar;
    public title_txt: TextField;
    public mcGoo: MovieClip;
    public hatcheryRemove5: buttonClose_CLIP;
    public mcCount1: MovieClip;
    public bProgress4: creatureBar;
    public bContinue: Button_CLIP;
    public hatcheryRemove4: buttonClose_CLIP;
    public bProgress3: creatureBar;
    public txtGuide: TextField;
    public bProgress2: creatureBar;
    public slot1: HatcheryMonsterIcon_CLIP;
    public scroller: ScrollSet_CLIP;
    public bFinish: MovieClip;
    public bProgress1: creatureBar;
    public slot2: HatcheryMonsterIcon_CLIP;
    public txtGoo: TextField;
    public txtStorage: TextField;
    public hatlabel4_txt: TextField;
    public hatcheryRemove1: buttonClose_CLIP;
    public slot3: HatcheryMonsterIcon_CLIP;
    public mcMagma: MovieClip;
    public hatlabel5_txt: TextField;
    public slot4: HatcheryMonsterIcon_CLIP;
    public hatcheryRemove3: buttonClose_CLIP;
    public tProgress5: TextField;
    public slot5: HatcheryMonsterIcon_CLIP;
    public txtMagma: TextField;
    public tGooLabel: TextField;
    public mcRemove3: buttonClose_CLIP;
    public hatcheryRemove2: buttonClose_CLIP;
    public tProgress4: TextField;
    public hatcheryBG2: MovieClip;
    public mcSlotsGoldFrame: MovieClip;
    public slot6: HatcheryMonsterIcon_CLIP;
    public bTopupMagma: MovieClip;
    public mcRemove2: buttonClose_CLIP;
    public tProgress3: TextField;
    public hatcheryBG3: MovieClip;
    public slot7: HatcheryMonsterIcon_CLIP;
    public mcFrame: frame_CLIP;
    public mcOverdrive: MovieClip;
    public hatlabel1_txt: TextField;
    public mcRemove1: buttonClose_CLIP;
    public tProgress2: TextField;
    public bTopup: MovieClip;
    public hatlabel2_txt: TextField;
    public mcCount6: MovieClip;
    public tProgress1: TextField;
    public hatcheryBG1: MovieClip;
    public bSpeedup: MovieClip;
    public tMagmaLabel: TextField;
    public mcStorage: MovieClip;
    public hatlabel3_txt: TextField;
    public mcRemove7: buttonClose_CLIP;
    public mcCount7: MovieClip;
    public hatchery4: HatcheryMonsterIcon_CLIP;

    constructor() {
        super();
        this.tHousingLabel = new TextField();
        this.mcRemove6 = new buttonClose_CLIP();
        this.hatchery5 = new HatcheryMonsterIcon_CLIP();
        this.mcCount4 = new MovieClip();
        this.mcRemove5 = new buttonClose_CLIP();
        this.mcCount5 = new MovieClip();
        this.hatchery2 = new HatcheryMonsterIcon_CLIP();
        this.hatcheryBG4 = new MovieClip();
        this.monsterCanvas = new MovieClip();
        this.mcRemove4 = new buttonClose_CLIP();
        this.mcMonsterInfo = new MovieClip();
        this.hatchery3 = new HatcheryMonsterIcon_CLIP();
        this.mcCount2 = new MovieClip();
        this.hatcheryBG5 = new MovieClip();
        this.monsterMask = new MovieClip();
        this.mcCount3 = new MovieClip();
        this.hatchery1 = new HatcheryMonsterIcon_CLIP();
        this.bProgress5 = new creatureBar();
        this.title_txt = new TextField();
        this.mcGoo = new MovieClip();
        this.hatcheryRemove5 = new buttonClose_CLIP();
        this.mcCount1 = new MovieClip();
        this.bProgress4 = new creatureBar();
        this.bContinue = new Button_CLIP();
        this.hatcheryRemove4 = new buttonClose_CLIP();
        this.bProgress3 = new creatureBar();
        this.txtGuide = new TextField();
        this.bProgress2 = new creatureBar();
        this.slot1 = new HatcheryMonsterIcon_CLIP();
        this.scroller = new ScrollSet_CLIP();
        this.bFinish = new MovieClip();
        this.bProgress1 = new creatureBar();
        this.slot2 = new HatcheryMonsterIcon_CLIP();
        this.txtGoo = new TextField();
        this.txtStorage = new TextField();
        this.hatlabel4_txt = new TextField();
        this.hatcheryRemove1 = new buttonClose_CLIP();
        this.slot3 = new HatcheryMonsterIcon_CLIP();
        this.mcMagma = new MovieClip();
        this.hatlabel5_txt = new TextField();
        this.slot4 = new HatcheryMonsterIcon_CLIP();
        this.hatcheryRemove3 = new buttonClose_CLIP();
        this.tProgress5 = new TextField();
        this.slot5 = new HatcheryMonsterIcon_CLIP();
        this.txtMagma = new TextField();
        this.tGooLabel = new TextField();
        this.mcRemove3 = new buttonClose_CLIP();
        this.hatcheryRemove2 = new buttonClose_CLIP();
        this.tProgress4 = new TextField();
        this.hatcheryBG2 = new MovieClip();
        this.mcSlotsGoldFrame = new MovieClip();
        this.slot6 = new HatcheryMonsterIcon_CLIP();
        this.bTopupMagma = new MovieClip();
        this.mcRemove2 = new buttonClose_CLIP();
        this.tProgress3 = new TextField();
        this.hatcheryBG3 = new MovieClip();
        this.slot7 = new HatcheryMonsterIcon_CLIP();
        this.mcFrame = new frame_CLIP();
        this.mcOverdrive = new MovieClip();
        this.hatlabel1_txt = new TextField();
        this.mcRemove1 = new buttonClose_CLIP();
        this.tProgress2 = new TextField();
        this.bTopup = new MovieClip();
        this.hatlabel2_txt = new TextField();
        this.mcCount6 = new MovieClip();
        this.tProgress1 = new TextField();
        this.hatcheryBG1 = new MovieClip();
        this.bSpeedup = new MovieClip();
        this.tMagmaLabel = new TextField();
        this.mcStorage = new MovieClip();
        this.hatlabel3_txt = new TextField();
        this.mcRemove7 = new buttonClose_CLIP();
        this.mcCount7 = new MovieClip();
        this.hatchery4 = new HatcheryMonsterIcon_CLIP();
        this.addFrameScript(0, this.frame1.bind(this));
    }

    private frame1(): void {
        this.stop();
    }
}
